language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
env:
    - DJANGO_PACKAGE="Django>=1.5,<1.6"
    - DJANGO_PACKAGE=https://github.com/django/django/archive/master.zip
install: pip install $DJANGO_PACKAGE --use-mirrors
script: python tests.py
